name: Test Automation Workflow

on:
  schedule:
    - cron: "30 23 * * *"   # Runs daily at 23:30 UTC
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Running Test Automation Framework with Maven
        run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: logs
          path: logs/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: extent-report
          path: report.html

      - name: Test Execution Status
        run: echo "Tests completed."
